# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'snapchatClone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for snapchatClone
    pod 'Firebase/Core'
    pod 'FirebaseUI/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'SDWebImage', '~> 4.0'
    #pod 'FirebaseUI'

end
